### PR TITLE
feat: logo component

### PR DESCRIPTION
**Pull request by kaf-lamed-beyt**
Hi @AdeboyeDN, kindly review. 

Light 👇🏼 
Screenshot from 2023-02-02 11-26-58

Dark 👇🏼 
Screenshot from 2023-02-02 11-27-08

### CODE REVIEW

**Comment by AdeboyeDN** [comment]
Yes this is great

**Comment by AdeboyeDN** [comment]
Screenshot_20230202-122353
So here is the logo I recommend you use for the dark mode.

**Comment by kaf-lamed-beyt** [comment]
Thanks!  I'll make the change.

**Comment by kaf-lamed-beyt** [comment]
Dang! 

Sorry, it is taking me a while to fix this. I had other tasks to complete, when I'm done, I'll update the code.

**Comment by kaf-lamed-beyt** [comment]
Hi @AdeboyeDN,

I realized that my former approach was too complex, and it didn't even work as it should. One thing that sorta hindered me also was the png images. I don't know why one of them was not being rendered at all, so I switched to the SVG format.

Below are the results. 

Light theme             |  Dark theme
:-------------------------:|:-------------------------:
pipeops documentation page in dark mode |  pipeops documentation page in dark light

**Comment by AdeboyeDN** [comment]
This looks great,
Thanks, man.

**Comment by kaf-lamed-beyt** [comment]
🚀

Please if any issue comes up in the future, I'd love to take it on.

**Pull request merged**
